export const INDUSTRIES = [
  { value: "Công nghệ thông tin", label: "Công nghệ thông tin" },
  { value: "Tài chính - Ngân hàng", label: "Tài chính - Ngân hàng" },
  { value: "Thương mại điện tử", label: "Thương mại điện tử" },
  { value: "AI & Machine Learning", label: "AI & Machine Learning" },
  { value: "Giáo dục & Đào tạo", label: "Giáo dục & Đào tạo" },
  { value: "Y tế & Sức khỏe", label: "Y tế & Sức khỏe" },
  { value: "Sản xuất", label: "Sản xuất" },
  { value: "Logistics & Chuỗi cung ứng", label: "Logistics & Chuỗi cung ứng" },
  { value: "Bất động sản", label: "Bất động sản" },
  { value: "Bán lẻ & Tiêu dùng", label: "Bán lẻ & Tiêu dùng" },
  { value: "Du lịch & Khách sạn", label: "Du lịch & Khách sạn" },
  { value: "Viễn thông", label: "Viễn thông" },
  { value: "Xây dựng & Kiến trúc", label: "Xây dựng & Kiến trúc" },
  { value: "Nông - Lâm - Ngư nghiệp", label: "Nông - Lâm - Ngư nghiệp" },
  { value: "Truyền thông & Giải trí", label: "Truyền thông & Giải trí" },
  { value: "Dịch vụ ăn uống (F&B)", label: "Dịch vụ ăn uống (F&B)" },
  { value: "Năng lượng & Môi trường", label: "Năng lượng & Môi trường" },
  { value: "Công nghiệp ô tô", label: "Công nghiệp ô tô" },
  { value: "Thời trang & May mặc", label: "Thời trang & May mặc" },
  { value: "Tư vấn doanh nghiệp", label: "Tư vấn doanh nghiệp" },
  { value: "Dược phẩm", label: "Dược phẩm" },
];